apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-image-registry
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  secretRef:
    name: installer-cloud-credentials
    namespace: openshift-image-registry
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AlibabaCloudProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - oss:CreateBucket
      - oss:DeleteBucket
      - oss:PutBucketTags
      - oss:GetBucketTags
      - oss:PutBucketAcl
      - oss:GetBucketAcl
      - oss:PutBucketEncryption
      - oss:GetBucketEncryption
      - oss:PutBucketLifecycle
      - oss:GetBucketLifecycle
      - oss:GetBucketLocation
      - oss:GetBucketInfo
      - oss:ListBucket
      - oss:GetObject
      - oss:PutObject
      - oss:DeleteObject
      - oss:ListMultipartUploads
      - oss:AbortMultipartUpload
      - oss:ListParts
      resource: "*"
  serviceAccountNames:
  - cluster-image-registry-operator
  - registry
